package SPReduce.utils;

public enum RecordType {
    TOTAL,COVERAGE_REDUCER, GLOBAL_REDUCER,H_GLOBAL_REDUCER, CALL_TRACE_REDUCER,ORIGIN_ORDER_REDUCER,RANDOM_TRACE_REDUCER, EXPRESSION_REDUCER, INLINE_REDUCER, LOCAL_EXPRESSION_REDUCER

}
