package SPReduce.reducer;

public enum ReducerType {
    COVERAGE_REDUCER, GLOBAL_REDUCER,H_GLOBAL_REDUCER, CALL_TRACE_REDUCER,RANDOM_TRACE_REDUCER,ORIGIN_ORDER_REDUCER, EXPRESSION_REDUCER, INLINE_REDUCER,LOCAL_EXPRESSION_REDUCER
}
